# Generated by Django 3.1.1 on 2020-10-04 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=1024)),
                ('audio_path', models.FileField(max_length=256, upload_to='origin/audio/')),
                ('video_path', models.FileField(max_length=256, upload_to='origin/video/')),
            ],
        ),
        migrations.CreateModel(
            name='UserAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_path', models.FileField(max_length=256, upload_to='user/audio/')),
                ('score', models.FloatField()),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaAPI.originmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
