# Generated by Django 3.0.8 on 2020-10-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tel',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openid',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
