# Generated by Django 3.0.8 on 2020-10-28 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraudio',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='media.OriginMedia'),
        ),
        migrations.RenameField(
            model_name='useraudio',
            old_name='level',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
    ]
