# Generated by Django 3.0.8 on 2020-11-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20201028_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraudio',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
