# Generated by Django 3.0.8 on 2020-11-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_auto_20201103_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Male'), ('2', 'Female')], max_length=1, null=True),
        ),
    ]
