# Generated by Django 3.0.8 on 2020-10-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_useraudio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAudio',
        ),
    ]
