# Generated by Django 3.0.8 on 2020-10-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_useraudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
