# Generated by Django 3.0.8 on 2020-10-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraudio',
            name='audio',
            field=models.FileField(max_length=512, upload_to='users/audio'),
        ),
    ]
