# Generated by Django 3.0.8 on 2020-10-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_auto_20201021_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
