# Generated by Django 3.0.8 on 2020-11-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='originmedia',
            name='speaker_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
