# Generated by Django 3.1.1 on 2020-10-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAudio',
        ),
    ]
