# Generated by Django 3.0.8 on 2020-11-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='originmedia',
            name='unique_level',
        ),
        migrations.AlterField(
            model_name='originmedia',
            name='type_id',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female')], default=0),
        ),
    ]
