# Generated by Django 3.0.8 on 2020-11-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_originmedia_speaker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='originmedia',
            name='type_id',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Male'), ('2', 'Female')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='originmedia',
            name='level_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name='originmedia',
            constraint=models.UniqueConstraint(fields=('level_id', 'type_id'), name='unique_level'),
        ),
    ]
