# Generated by Django 3.1.1 on 2020-10-21 07:32

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_delete_useraudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='originmedia',
            name='media_id',
            field=models.IntegerField(default=media.models.OriginMedia.media_id_default, unique=True),
        ),
    ]
