# Generated by Django 3.1.1 on 2020-10-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_delete_useraudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='originmedia',
            name='media_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
