# Generated by Django 3.0.8 on 2020-11-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_originmedia_speaker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='originmedia',
            name='type_id',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Male'), ('2', 'Female')], default='0', max_length=1),
        ),
    ]
